version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data/db:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test